version: '3'
services:
  web:   
      image: nginx:alpine
      container_name: nginx-container  
      ports:	
        - ${NGINX_SERVER_PORT}:80
      volumes:
      - ${PROJECT_PATH}:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./logs/nginx:/var/log/nginx
  
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ${PROJECT_PATH}:/app
      - ./logs/php:/var/log/php
      
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysqldata:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    ports:
      - ${MYSQL_PORT}:3306
    
  composer:
    image: composer:lts
    #command: ["composer", "install"]
    volumes:
      - ${PROJECT_PATH}:/app
       
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 8081:80
    
  adminer_container:
    image: adminer:latest
    environment: 
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DESIGN: hever
    ports: 
      - 8082:80
    
volumes:
    mysqldata: {}

